### ISSUE TITLE
Avoid shiftIn in SPI bit-bang

### ISSUE THREAD

**Issue by bemasher** [bemasher/MAX31855#1]
Avoid use of shiftIn for bit-banging SPI to reduce clock jitter between calls. This shouldn't affect performance of actually reading data but might prevent strange error states.

![shiftin](https://cloud.githubusercontent.com/assets/79724/3007189/a4d449e8-de72-11e3-91e2-11432f91aead.png)

**Comment by rakeshscetic** [comment]
Hello Mate,

 I am facing problem reading the probe value. I could read internal temperature perfect, but while reading the probe temperature its always giving me -ve value.. I am able to read the Open circuit bit correctly. 

Kindly guide me for bit bang implementation. 

Thanks
Rakesh

**Comment by heypete** [comment]
Could you please clarify what you mean by "-ve" value?
